/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SampleProject;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
	  String input1="noon";
	  Library app=new Library();
	  boolean expected=true;
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.isPalindrome(input1));
    }
}
